<?php
return array (
  'user_name' => 
  array (
    'fieldid' => '108',
    'modelid' => '12',
    'siteid' => '1',
    'field' => 'user_name',
    'name' => '您的姓名',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^[\\x7f-\\xff]+$/',
    'errortips' => '请输入正确的姓名！',
    'formtype' => 'text',
    'setting' => '{"size":"50","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '50',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'user_phone' => 
  array (
    'fieldid' => '109',
    'modelid' => '12',
    'siteid' => '1',
    'field' => 'user_phone',
    'name' => '您的电话',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '请输入正确的手机号！',
    'formtype' => 'number',
    'setting' => '{"minnumber":"1","maxnumber":"","decimaldigits":"0","size":"","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'minnumber' => '1',
    'maxnumber' => '',
    'decimaldigits' => '0',
    'size' => '',
    'defaultvalue' => '',
  ),
  'user_intention' => 
  array (
    'fieldid' => '110',
    'modelid' => '12',
    'siteid' => '1',
    'field' => 'user_intention',
    'name' => '咨询意向',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => '{"width":"100%","height":"46","defaultvalue":"","enablehtml":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>